[project]
name = "gen-ai"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Tapabrata Chowdhury", email = "tapabratachowdhury12@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "aiohappyeyeballs",
    "aiohttp",
    "aiosignal",
    "annotated-types",
    "anyio",
    "appnope",
    "arxiv",
    "asttokens",
    "attrs",
    "beautifulsoup4",
    "brotli",
    "brotlicffi",
    "certifi",
    "cffi",
    "charset-normalizer",
    "click",
    "colorama",
    "comm",
    "dataclasses-json",
    "ddgs",
    "debugpy",
    "decorator",
    "distro",
    "executing",
    "fake-useragent",
    "feedparser",
    "frozenlist",
    "greenlet",
    "groq",
    "h11",
    "h2",
    "hpack",
    "httpcore",
    "httpx",
    "httpx-sse",
    "hyperframe",
    "idna",
    "ipykernel",
    "ipython",
    "ipython-pygments-lexers",
    "jedi",
    "jsonpatch",
    "jsonpointer",
    "jupyter-client",
    "jupyter-core",
    "langchain",
    "langchain-chroma",
    "langchain-classic",
    "langchain-community",
    "langchain-core",
    "langchain-groq",
    "langchain-nvidia-ai-endpoints",
    "langchain-protocol",
    "langchain-text-splitters",
    "langgraph",
    "langgraph-checkpoint",
    "langgraph-prebuilt",
    "langgraph-sdk",
    "langsmith",
    "lxml",
    "marshmallow",
    "matplotlib-inline",
    "multidict",
    "mypy-extensions",
    "nest-asyncio",
    "numpy",
    "orjson",
    "ormsgpack",
    "packaging",
    "parso",
    "pexpect",
    "platformdirs",
    "primp",
    "prompt-toolkit",
    "propcache",
    "psutil",
    "ptyprocess",
    "pure-eval",
    "pycparser",
    "pydantic",
    "pydantic-core",
    "pydantic-settings",
    "pygments",
    "pymupdf",
    "pypdf",
    "python-dateutil",
    "python-dotenv",
    "pyyaml",
    "pyzmq",
    "requests",
    "requests-toolbelt",
    "sgmllib3k",
    "six",
    "sniffio",
    "socksio",
    "soupsieve",
    "sqlalchemy",
    "stack-data",
    "tenacity",
    "tornado",
    "traitlets",
    "typing-extensions",
    "typing-inspect",
    "typing-inspection",
    "urllib3",
    "uuid-utils",
    "wcwidth",
    "wikipedia",
    "xxhash",
    "yarl",
    "zstandard",
]
